import { Box } from "@mui/material";
import AppFooter from "components/AppFooter";
import AppHeader from "components/AppHeader";
import Head from "next/head";
import React from "react";

const BaseLayout = ({ children }) => {
	return (
		<Box>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<AppHeader />
			<Box sx={{ marginTop: "128px" }}>{children}</Box>
			<AppFooter />
		</Box>
	);
};

export default BaseLayout;
